server:
  port: 8084

spring:
  application:
    name: transaction-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank_app
    username: santhosh
    password: saiviyan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  kafka:
#    producer:
#      bootstrap-servers: localhost:29092

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://host.docker.internal:8761/eureka/